CXX = g++
CXXFLAGS = -std=c++17 -Wall -Wextra
GTEST_LIBS = -lgtest -lgtest_main -pthread

kettle: main.cpp
	$(CXX) $(CXXFLAGS) -o $@ $<

test_kettle: kettle_tests.cpp
	$(CXX) $(CXXFLAGS) $< -o $@ $(GTEST_LIBS)

.PHONY: test clean

test: test_kettle
	./test_kettle

clean:
	rm -f kettle test_kettle